#ifndef _SOC_MICROCHIP_PIC32_PIC32CM2564_SOC_H_
#define _SOC_MICROCHIP_PIC32_PIC32CM2564_SOC_H_

#ifndef _ASMLANGUAGE

#define DONT_USE_CMSIS_INIT

#include <zephyr/types.h>

#if defined(CONFIG_SOC_PIC32CM2564)
#include <pic32cm2564.h>
#include <lan8660.h>
#else
#error Library does not support the specified device.
#endif

#endif /* _ASMLANGUAGE */

#include "microchip_pic32_dt.h"

/** Processor Clock (HCLK) Frequency */
#define SOC_MICROCHIP_PIC32_HCLK_FREQ_HZ MICROCHIP_PIC32_DT_CPU_CLK_FREQ_HZ

/** Master Clock (MCK) Frequency */
#define SOC_MICROCHIP_PIC32_MCK_FREQ_HZ SOC_MICROCHIP_PIC32_HCLK_FREQ_HZ

/** Known values */
#define SOC_MICROCHIP_PIC32_OSC32K_FREQ_HZ		32768
#define SOC_MICROCHIP_PIC32_GCLK1_TARGET_FREQ_HZ	31250

/** GCLK1 source frequency selector */
#if defined(CONFIG_SOC_ATMEL_SAMD_XOSC32K_AS_MAIN)
#define SOC_MICROCHIP_PIC32_GCLK1_SRC_FREQ_HZ SOC_MICROCHIP_PIC32_OSC32K_FREQ_HZ
#endif

/** DFLL48M output frequency */
#define SOC_MICROCHIP_PIC32_DFLL48M_FREQ_HZ	\
	(SOC_MICROCHIP_PIC32_MCK_FREQ_HZ * SOC_ATMEL_SAM0_GCLK0_DIV)

/** Dividers and frequency for GCLK1 */
#define SOC_MICROCHIP_PIC32_GCLK1_DIV	\
	(SOC_MICROCHIP_PIC32_GCLK1_SRC_FREQ_HZ / SOC_MICROCHIP_PIC32_GCLK1_TARGET_FREQ_HZ)
#define SOC_MICROCHIP_PIC32_GCLK1_FREQ_HZ	\
	(SOC_MICROCHIP_PIC32_GCLK1_SRC_FREQ_HZ / SOC_MICROCHIP_PIC32_GCLK1_DIV)

/** DFLL48M output multiplier */
#define SOC_ATMEL_SAM0_DFLL48M_MUL	\
	(SOC_MICROCHIP_PIC32_DFLL48M_FREQ_HZ / SOC_MICROCHIP_PIC32_GCLK1_FREQ_HZ)

#endif
