/*
 * Copyright (c) 2025 Microchip Technology Inc.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ZEPHYR_DRIVERS_ETHERNET_ETH_PIC32_GMAC_H_
#define ZEPHYR_DRIVERS_ETHERNET_ETH_PIC32_GMAC_H_

/*
 * Map the SAM-family DFP GMAC register names to the PIC32-family DFP GMAC
 * register names.
 */

#define Gmac		gmac_registers_t

#define GMAC_NCR        GMAC_NETWORK_CONTROL
#define GMAC_NCFGR      GMAC_NETWORK_CONFIG
#define GMAC_DCFGR      GMAC_DMA_CONFIG
#define GMAC_RBQB	GMAC_RECEIVE_Q_PTR
#define GMAC_TBQB       GMAC_TRANSMIT_Q_PTR
#define GMAC_ISR        GMAC_INT_STATUS
#define GMAC_IER        GMAC_INT_ENABLE
#define GMAC_IDR        GMAC_INT_DISABLE
#define GMAC_SA		GMAC_SPEC_ADD1_BOTTOM
#define GMAC_HRB        GMAC_HASH_BOTTOM
#define GMAC_HRT        GMAC_HASH_TOP

#define GMAC_NCR_TSTART	GMAC_NETWORK_CONTROL_TX_START_PCLK_Msk
#define GMAC_NCR_TXEN	GMAC_NETWORK_CONTROL_ENABLE_TRANSMIT_Msk
#define GMAC_NCR_RXEN	GMAC_NETWORK_CONTROL_ENABLE_RECEIVE_Msk
#define GMAC_NCR_CLRSTAT	GMAC_NETWORK_CONTROL_CLEAR_ALL_STATS_REGS_Msk
#define GMAC_NCR_MPE	GMAC_NETWORK_CONTROL_MAN_PORT_EN_Msk
#define GMAC_NCFGR_MTIHEN	GMAC_NETWORK_CONFIG_MULTICAST_HASH_ENABLE_Msk
#define GMAC_NCFGR_LFERD	GMAC_NETWORK_CONFIG_LENGTH_FIELD_ERROR_FRAME_DISCARD_Msk
#define GMAC_NCFGR_RFCS		GMAC_NETWORK_CONFIG_FCS_REMOVE_Msk
#define GMAC_NCFGR_RXCOEN	GMAC_NETWORK_CONFIG_RECEIVE_CHECKSUM_OFFLOAD_ENABLE_Msk

#define GMAC_NCFGR_FD	GMAC_NETWORK_CONFIG_FULL_DUPLEX_Msk
#define GMAC_NCFGR_SPD	GMAC_NETWORK_CONFIG_SPEED_Msk

#define	GMAC_ISR_TCOMP	GMAC_INT_STATUS_TRANSMIT_COMPLETE_Msk
#define GMAC_ISR_RCOMP	GMAC_INT_STATUS_RECEIVE_COMPLETE_Msk

#define GMAC_IER_HRESP	GMAC_INT_ENABLE_ENABLE_RESP_NOT_OK_INTERRUPT_Msk
#define GMAC_IER_TFC	GMAC_INT_ENABLE_ENABLE_TRANSMIT_FRAME_CORRUPTION_DUE_TO_AMBA_ERROR_INTERRUPT_Msk
#define GMAC_IER_RLEX	GMAC_INT_ENABLE_ENABLE_RETRY_LIMIT_EXCEEDED_OR_LATE_COLLISION_INTERRUPT_Msk
#define GMAC_IER_TUR	GMAC_INT_ENABLE_ENABLE_TRANSMIT_BUFFER_UNDER_RUN_INTERRUPT_Msk
#define GMAC_IER_ROVR	GMAC_INT_ENABLE_ENABLE_RECEIVE_OVERRUN_INTERRUPT_Msk
#define GMAC_IER_RXUBR	GMAC_INT_ENABLE_ENABLE_RECEIVE_USED_BIT_READ_INTERRUPT_Msk
#define GMAC_IER_TCOMP	GMAC_INT_ENABLE_ENABLE_TRANSMIT_COMPLETE_INTERRUPT_Msk
#define GMAC_IER_RCOMP	GMAC_INT_ENABLE_ENABLE_RECEIVE_COMPLETE_INTERRUPT_Msk

#define GMAC_DCFGR_FBLDO_INCR4	GMAC_DMA_CONFIG_AMBA_BURST_LENGTH(2)
#define GMAC_DCFGR_DRBS(value)	GMAC_DMA_CONFIG_RX_BUF_SIZE(value)

#define GMAC_NCFGR_CLK(value)	GMAC_NETWORK_CONFIG_MDC_CLOCK_DIVISION(value)

#define GMAC_NCFGR_CLK_MCK_8    GMAC_NCFGR_CLK(0)
#define GMAC_NCFGR_CLK_MCK_16   GMAC_NCFGR_CLK(1)
#define GMAC_NCFGR_CLK_MCK_32   GMAC_NCFGR_CLK(2)
#define GMAC_NCFGR_CLK_MCK_48   GMAC_NCFGR_CLK(3)
#define GMAC_NCFGR_CLK_MCK_64   GMAC_NCFGR_CLK(4)
#define GMAC_NCFGR_CLK_MCK_96   GMAC_NCFGR_CLK(5)

#define GMAC_DMA_CONFIG_RX_PBUF_SIZE_FULL_Val       0x3
#define GMAC_DMA_CONFIG_AMBA_BURST_LENGTH_INCR4_Val 0x4

#endif /* ZEPHYR_DRIVERS_ETHERNET_ETH_PIC32_GMAC_H_ */
